version: 0.2
phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_ENDPOINT
      - docker build -t pokemon-client-ecr-repo ./client/.
      - docker build -t pokemon-server-ecr-repo ./server/.
      - docker tag pokemon-client-ecr-repo:latest $CLIENT_ECR_IMAGE_URL:latest
      - docker tag pokemon-server-repo:latest $SERVER_ECR_IMAGE_URL:latest
      - echo $ECR_IMAGE_URL
      - docker push $CLIENT_ECR_IMAGE_URL:latest
      - docker push $SERVER_ECR_IMAGE_URL:latest

# docker push 967411324500.dkr.ecr.eu-west-2.amazonaws.com/forex-ecr-repo:latest

# Retrieve an authentication token and authenticate your Docker client to your registry.
# Use the AWS CLI:
# aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 967411324500.dkr.ecr.eu-west-2.amazonaws.com

# Note: If you receive an error using the AWS CLI, make sure that you have the latest version of the AWS CLI and Docker installed.
# Build your Docker image using the following command. For information on building a Docker file from scratch see the instructions here . You can skip this step if your image is already built:
# docker build -t forex-ecr-repo .

# After the build completes, tag your image so you can push the image to this repository:
# docker tag forex-ecr-repo:latest 967411324500.dkr.ecr.eu-west-2.amazonaws.com/forex-ecr-repo:latest

# Run the following command to push this image to your newly created AWS repository:
# docker push 967411324500.dkr.ecr.eu-west-2.amazonaws.com/forex-ecr-repo:latest